### ISSUE TITLE
Migrate over Cookbook content

### ISSUE THREAD

**Issue by mgrover1** [ProjectPythia/cookbook-actions#27]
# Updating Project Pythia Cookbook Infrastructure

## Github Actions (Each cookbook repo)
- [x] Replace in all actions (ProjectPythiaCookbooks --> ProjectPythia)
- [x] URL in the description
- [x] Example code in README
- [x] Badges in README

## Cookbook Gallery
- [x] Update the cookbook gallery over, update the associated links

## Contribution Guide
- [x] Update links/content related to contributing a cookbook

**Comment by brian-rose** [comment]
Looks like this work is all done!
