### ISSUE TITLE
Enable comments on both user and project pages

### ISSUE THREAD

**Issue by jbusecke** [ProjectPythia/cookbook-actions#47]
Currently [this line](https://github.com/ProjectPythia/cookbook-actions/blob/6dbeaf8e9cadb0d8f6467d4ac0cdedb0f079320b/.github/workflows/preview-comment.yaml#L75) assumes that the current page is being deployed as a 'Project Site'. It would be amazing if the workflow could also support 'User/Org Sites' ([definitions](https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#types-of-github-pages-sites)) as e.g. implemented in https://github.com/leap-stc/leap-stc.github.io.

I believe this could be implemented with some input argument `project_site` (default to true) which switches the line from

```
✅ Deployment Preview URL: https://${{ github.repository_owner }}.github.io/${{ steps.repo-name.outputs.value }}/_preview/${{ inputs.pull_request_number }}
```

to this for false:
```
✅ Deployment Preview URL: https://${{ github.repository_owner }}.github.io/${{ inputs.pull_request_number }}
```

Happy to submit a PR, but I am not quite sure what the best way to express this is.

**Comment by brian-rose** [comment]
It turns out that we need this for previewing our own main project site https://github.com/ProjectPythia/projectpythia.github.io (which publishes to https://projectpythia.org).

I will work on a solution!

**Comment by brian-rose** [comment]
The most elegant / robust way to achieve this would be to query the repository to find its GitHub Pages URL. Then we wouldn't have to implement any complicated logic for constructing the preview URL, it would just be `{default Pages URL}/_preview/{PR number}`.

I did some googling but unfortunately didn't find any way to access the URL from within an action.

**Comment by brian-rose** [comment]
A workaround that still avoids needing to implement another input argument is just to parse the repo name to see if it contains the string `github.io`, which would then indicate that this is *not* a project site.

I'm trying to think of possible use cases where this wouldn't work, but I'm drawing a blank.

**Comment by brian-rose** [comment]
This is implemented now in https://github.com/ProjectPythia/cookbook-actions/pull/59
(after a few bits of trial and error in previous PRs).

@jbusecke take a look! The workflows now automatically detect whether they are dealing with an org site or project site and adapt the preview URL accordingly.

**Comment by brian-rose** [comment]
Closing as I think this has been resolved, but feel free to reopen for more discussion!

**Comment by jbusecke** [comment]
Ill def try that in the next week! Thank you for all the work here!
