### ISSUE TITLE
Binderbot builds don't work with authentication

### ISSUE THREAD

**Issue by brian-rose** [ProjectPythia/cookbook-actions#64]
As discussed [here](https://github.com/ProjectPythia/HRRR-AWS-cookbook/pull/19), the new Pythia binder service at https://binder.projectpythia.org requires GitHub authentication.

Currently our binderbot build doesn't support this.

I've looked through the binderbot code, as well as some of the docs for BinderHub to try to understand how to make this work. But I'm out of my depth.

It seems to me that if we keep the BinderHub configured to require this authentication, then we'll have to create a dummy GitHub user to supply credentials for all our automated CI runs.

An alternative might be to relax the authentication requirement for users originating from within the ProjectPythia org. I have no idea if this is possible or how to implement this.

A third option might be to drop the authentication requirement entirely until after the hackathon, giving us some time to figure this out.

**Comment by brian-rose** [comment]
There's also a restriction currently to one server session per user. So even if our nightly builds and other CI tests were authenticating via a dummy GitHub user profile, they would not be able to run concurrently.

**Comment by brian-rose** [comment]
At today's IWG we agreed to remove the authentication for the hackathon week, but a solution to this problem will still be needed for the future.

**Comment by brian-rose** [comment]
This is temporarily resolved since authentication has been removed from the BinderHub.

Changing the title to reflect the post-hackathon task of figuring out how to make it work with authentication!

**Comment by ktyle** [comment]
@brian-rose given that we would like to re-enable authtentication on our BinderHub, do you see any immediate path forward?

**Comment by brian-rose** [comment]
> @brian-rose given that we would like to re-enable authtentication on our BinderHub, do you see any immediate path forward?

No I don't unfortunately. I think this may require technical expertise with BinderHub / JupyterHub / binderbot that I don't have.

**Comment by jukent** [comment]
2I2C may have some expertise here

**Comment by brian-rose** [comment]
2i2c likely has the relevant expertise to solve this problem. Hopefully we can tackle this early during the next phase of Pythia when our formal collaboration with 2i2c gets going.

**Comment by mgrover1** [comment]
This has been implemented with current secrets in the workflows https://github.com/ProjectPythia/cookbook-actions/blob/main/.github/workflows/build-book.yaml#L197, we still need documentation on this.
