### ISSUE TITLE
Unpin `sphinxcontrib-...` packages back

### ISSUE THREAD

**Issue by erogluorhan** [ProjectPythia/cookbook-actions#93]
Several `sphinxcontrib-...` packages' new versions have been released over the weekend of Jan 13 & 14, 2024, and they started to require Sphinx 5.0 that led our cookbook builds to fail. 

To temporarily overcome this situation, PR #91 and PR #92 have been realized. Once the permanent Sphinx theme update is performed (in [ProjectPythia/sphinx-pythia-theme - Issue #39](https://github.com/ProjectPythia/sphinx-pythia-theme/issues/39)), these PR's pinnings need to be reverted.

**Comment by brian-rose** [comment]
Now that pythia-sphinx-theme v2024.3.0 is released, it's time to remove these pins.
